apiVersion: batch/v1
kind: Job
metadata:
  name: webhook-cert-setup
spec:
  template:
    spec:
      serviceAccountName: webhook-cert-sa
      containers:
      - name: webhook-cert-setup
        # This is a minimal kubectl image based on Alpine Linux that signs certificates using the k8s extension api server
        image: bmutziu/k8s-webhook-cert-manager:latest
        command: ["./generate_certificate.sh"]
        args:
          - "--service"
          - "hello-webhook-service"
          - "--webhook"
          - "hello-webhook.bmutziu.me"
          - "--secret"
          - "hello-tls-secret"
          - "--namespace"
          - "default"
      restartPolicy: Never
  backoffLimit: 3
